### ISSUE TITLE
TypeError: AppScripts.serve is not a function

### ISSUE THREAD

**Issue by edwin-chui-seagull-com** [loiane/ionic2-pokedex#13]
Hello, when I try to execute the command ionic serve the error appears. This happens with the following parameters:

cli packages: (...\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 0.0.45
    Ionic Framework    : ionic-angular 2.0.0-rc.3

System:

    Node : v6.11.1
    npm  : 3.10.10
    OS   : Windows 10

**Comment by loiane** [comment]
Hi, this project version does not work with cli 3.x
You can try and copy the code only to a new ionic 3 project.
I'm planning to update the code to latest cli soon!
