### ISSUE TITLE
why do you choose ionic?

### ISSUE THREAD

**Issue by BruceAndLee** [loiane/ionic2-pokedex#15]
why do you choose ionic?

**Comment by loiane** [comment]
Hi, I'm a web developer. For mobile development, I can leverage my knowledge of angular, javascript/html/css. I created this project as a hobby as I'm familiar with the technologies used by Ionic (angular + cordova).
But you can achieve similar results using other mobile frameworks such as react native, native javascript, pure  javascript/html/css + cordova, xamarim - or even go native with android/ios.

**Comment by BruceAndLee** [comment]
> Hi, I'm a web developer. For mobile development, I can leverage my knowledge of angular, javascript/html/css. I created this project as a hobby as I'm familiar with the technologies used by Ionic (angular + cordova).
> But you can achieve similar results using other mobile frameworks such as react native, native javascript, pure javascript/html/css + cordova, xamarim - or even go native with android/ios.

Thanks for your reply, I'm a chinese programer based on dotnet platform,Can I become your friend?

**Comment by BruceAndLee** [comment]
> Hi, I'm a web developer. For mobile development, I can leverage my knowledge of angular, javascript/html/css. I created this project as a hobby as I'm familiar with the technologies used by Ionic (angular + cordova).
> But you can achieve similar results using other mobile frameworks such as react native, native javascript, pure javascript/html/css + cordova, xamarim - or even go native with android/ios.

https://www.51mordern.com, please known

**Comment by Zichis** [comment]
It's easier for someone who already has web development skills.

**Comment by BruceAndLee** [comment]
> It's easier for someone who already has web development skills.

Thanks，my skill site:www.51mordern.com
