### ISSUE TITLE
Error on Ionic Project

### ISSUE THREAD

**Issue by dsoldera** [loiane/ionic2-pokedex#4]
Hello Loiane,

I´ve downloaded you project and followed the steps to run the project, but I'm founding a few errors. Could you please take a look at it?

Thanks.
![2016-11-19_2159](https://cloud.githubusercontent.com/assets/11474555/20459310/7186ec86-aea3-11e6-80c1-59c956aec022.png)

**Comment by loiane** [comment]
Hi Dani,

These issues are due the update to rc 3. There are some missing files in my current project. I'm merging a PR so this is fixed, and then you can pull the changes and try again pls.

**Comment by dsoldera** [comment]
Nice. Thanks @loiane  =)
